##
# Validates lint on the project
##

name: Lint

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0

      - uses: actions/setup-node@v4.0.4
        with:
          node-version-file: '.nvmrc'

      - run: npm ci
      - run: npm run lint
